import json
import uuid
import asyncio
from typing import Optional
from pydantic import BaseModel
from fastapi import APIRouter, Depends, Request, HTTPException, BackgroundTasks

class CompletePlanRequest(BaseModel):
    day: Optional[int] = None
    days: Optional[int] = None
    custom_instructions: Optional[str] = None
from sqlalchemy.orm import Session
from db.session import get_db, SessionLocal
from services.meal_plan_ai import generate_meal_plan
from services.health_plan_ai import generate_complete_health_plan
from db.models.food import FoodItem
from db.models.plan import Plan, PlanItem
from schemas.plan import GeneratedPlanSchema
from utils import get_day_name
from services.nutrition import filter_foods_for_plan, food_to_dict
from core.config import settings

router = APIRouter(
    prefix="/v1/generate-plan",
    tags=["Generate AI Plan"]
)

TASKS = {}


def _food_list_for_user(db: Session, user_profile: dict):
    from sqlalchemy import or_
    foods = (
        db.query(FoodItem)
        .filter(or_(FoodItem.user_id.is_(None), FoodItem.source == "system"))
        .all()
    )
    if not foods:
        foods = db.query(FoodItem).all()
    bounded = filter_foods_for_plan(foods, user_profile.get("dietary_prefs"), settings.MAX_PLAN_FOOD_ITEMS)
    return [food_to_dict(f) for f in bounded]


def _persist_meal_plan(db: Session, user_id: int, plan_data: GeneratedPlanSchema, days: int):
    from datetime import datetime
    from pytz import timezone
    user_tz = timezone("Asia/Kolkata")
    local_now = datetime.now(user_tz)
    formatted_time = local_now.strftime("%d-%m-%Y %I:%M %p")
    plan_name = f"AI Meal Plan ({formatted_time})"

    existing_plan = (
        db.query(Plan)
        .filter(Plan.user_id == user_id)
        .order_by(Plan.id.desc())
        .first()
    )
    if existing_plan:
        db.query(PlanItem).filter(PlanItem.plan_id == existing_plan.id).delete()
        existing_plan.name = plan_name
        existing_plan.description = "Updated by AI"
        plan_record = existing_plan
    else:
        plan_record = Plan(
            user_id=user_id,
            name=plan_name,
            description="Generated by AI"
        )
        db.add(plan_record)
        db.commit()
        db.refresh(plan_record)

    for meal in plan_data.meals:
        for item in meal.items:
            db.add(PlanItem(
                plan_id=plan_record.id,
                food_id=item.food_id,
                quantity=item.quantity,
                unit=item.unit,
                meal_name=meal.meal,
                day=plan_data.day
            ))
    db.commit()
    return plan_record


def _persist_complete_plan(db: Session, user_id: int, plan, target_day: int):
    plan_dict = plan.model_dump()
    plan_dict = json.loads(json.dumps(plan_dict, default=float))
    
    from datetime import datetime
    from pytz import timezone
    user_tz = timezone("Asia/Kolkata")
    local_now = datetime.now(user_tz)
    day_int = int(local_now.strftime("%d"))
    month_year = local_now.strftime("%B, %Y")
    plan_name = f"{day_int} {month_year} Health Plan"

    existing_plan = (
        db.query(Plan)
        .filter(Plan.user_id == user_id)
        .order_by(Plan.id.desc())
        .first()
    )
    if existing_plan:
        db.query(PlanItem).filter(PlanItem.plan_id == existing_plan.id).delete()
        existing_plan.name = plan_name
        existing_plan.description = "Complete Health Plan Updated by AI"
        existing_plan.workout_plan = plan_dict.get("workout_plan")
        existing_plan.avoidance_list = plan_dict.get("avoidance_list")
        existing_plan.budget_tips = plan_dict.get("budget_tips")
        plan_record = existing_plan
    else:
        plan_record = Plan(
            user_id=user_id,
            name=plan_name,
            description="Complete Health Plan Generated by AI",
            workout_plan=plan_dict.get("workout_plan"),
            avoidance_list=plan_dict.get("avoidance_list"),
            budget_tips=plan_dict.get("budget_tips")
        )
        db.add(plan_record)
        db.commit()
        db.refresh(plan_record)

    for meal in plan.meal_plan:
        for item in meal.items:
            db.add(PlanItem(
                plan_id=plan_record.id,
                food_id=item.food_id,
                quantity=item.quantity,
                unit=item.unit,
                meal_name=meal.meal,
                day=plan.day
            ))
    db.commit()
    return plan_record, plan_dict


def _generate_plan_task(task_id: str, user_id: int, days: int, user_profile: dict):
    db = SessionLocal()
    try:
        TASKS[task_id] = {"status": "processing"}
        food_list = _food_list_for_user(db, user_profile)
        raw_plan = generate_meal_plan(user_profile, food_list, days)

        if isinstance(raw_plan, GeneratedPlanSchema):
            plan_data = raw_plan
        else:
            plan_data = GeneratedPlanSchema.model_validate(raw_plan)

        plan_record = _persist_meal_plan(db, user_id, plan_data, days)
        plan_dict = json.loads(json.dumps(plan_data.model_dump(), default=float))
        TASKS[task_id] = {
            "status": "completed",
            "plan_id": plan_record.id,
            "plan": plan_dict
        }
    except Exception as e:
        TASKS[task_id] = {"status": "failed", "error": str(e)}
    finally:
        db.close()


async def _generate_complete_plan_task(task_id: str, user_id: int, target_day: int, user_profile: dict, custom_instructions: str | None = None):
    db = SessionLocal()
    try:
        TASKS[task_id] = {"status": "processing", "message": "Agents coordinating meal + workout plans…"}
        food_list = _food_list_for_user(db, user_profile)

        plan = await generate_complete_health_plan(user_profile, food_list, target_day, custom_instructions)
        plan_record, plan_dict = _persist_complete_plan(db, user_id, plan, target_day)

        TASKS[task_id] = {
            "status": "completed",
            "plan_id": plan_record.id,
            "plan": plan_dict,
            "message": "Complete health plan generated successfully via LangGraph Agents",
        }
    except Exception as e:
        TASKS[task_id] = {"status": "failed", "error": str(e)}
    finally:
        db.close()


@router.post("/")
def auto_generate_plan(request: Request, background_tasks: BackgroundTasks, days: int = 1):
    current_user = request.state.user

    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi or 22.0
    }

    task_id = str(uuid.uuid4())
    TASKS[task_id] = {"status": "pending"}
    background_tasks.add_task(_generate_plan_task, task_id, current_user.id, days, user_profile)

    return {
        "message": "AI meal plan generation started",
        "task_id": task_id
    }


@router.get("/status/{task_id}")
def get_task_status(task_id: str):
    task = TASKS.get(task_id)
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")
    if task.get("status") in ("completed", "failed"):
        return TASKS.pop(task_id)
    return task


@router.post("/complete")
async def auto_generate_complete_plan(
    request: Request,
    background_tasks: BackgroundTasks,
    body: CompletePlanRequest = None,
):
    """Start async complete health plan generation. Poll GET /status/{task_id}."""
    from datetime import datetime
    from pytz import timezone
    day = body.day if body else None
    days = body.days if body else None
    custom_instructions = body.custom_instructions if body else None

    user_tz = timezone("Asia/Kolkata")
    current_day = datetime.now(user_tz).weekday() + 1
    target_day = day if day is not None else (days if days is not None else current_day)
    current_user = request.state.user

    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi or 22.0,
        "allergies": current_user.allergies,
        "budget": current_user.budget
    }

    task_id = str(uuid.uuid4())
    TASKS[task_id] = {"status": "pending", "message": "Queued"}
    background_tasks.add_task(
        _generate_complete_plan_task, task_id, current_user.id, target_day, user_profile, custom_instructions
    )

    return {
        "message": "Complete health plan generation started",
        "task_id": task_id,
        "status": "pending",
    }


@router.post("/complete/sync")
async def auto_generate_complete_plan_sync(
    request: Request,
    body: CompletePlanRequest = None,
    db: Session = Depends(get_db),
):
    """Synchronous complete plan (legacy / debugging). Prefer /complete + status poll."""
    from datetime import datetime
    from pytz import timezone
    day = body.day if body else None
    days = body.days if body else None
    custom_instructions = body.custom_instructions if body else None

    user_tz = timezone("Asia/Kolkata")
    current_day = datetime.now(user_tz).weekday() + 1
    target_day = day if day is not None else (days if days is not None else current_day)
    current_user = request.state.user

    food_list = _food_list_for_user(db, {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
    })

    user_profile = {
        "dietary_prefs": current_user.dietary_prefs,
        "goals": current_user.goals,
        "bmi": current_user.bmi,
        "allergies": current_user.allergies,
        "budget": current_user.budget
    }

    try:
        plan = await generate_complete_health_plan(user_profile, food_list, target_day, custom_instructions)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Graph execution failed: {e}")

    plan_record, plan_dict = _persist_complete_plan(db, current_user.id, plan, target_day)
    return {
        "message": "Complete health plan generated successfully via LangGraph Agents",
        "plan_id": plan_record.id,
        "plan": plan_dict
    }
